server:
  port: 11004

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  activemq:
    broker-url: tcp://localhost:61616
jms:
  PurchaseTopic: PurchaseTopic
  pub-sub-domain: true


profiles:
  active:
  - default
data:
  rest:
    base-path: /

# H2
datasource:
  url: jdbc:h2:mem:test
  driverClassName: org.h2.Driver
  username: sa
  password:
  
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: create-drop
      
service-urls:
  shop-account: /v1/kmmoc/account
      